# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = ENV['DOCUSIGN_ACCOUNT_USERNAME']
  config.password       = ENV['DOCUSIGN_ACCOUNT_PW']
  config.integrator_key = ENV['DOCUSIGN_API_KEY']
  config.account_id     = '7458607'
  config.endpoint       = 'https://docusign.net/restapi'
  config.api_version    = 'v2'
  config.open_timeout   = 2 # default value is 5
  config.read_timeout   = 5 # default value is 10
end

